Question 1: Array Creation  
1.1 Create a 1D array of integers from 5 to 25 using NumPy. 

In [19]:
import numpy as np

arr1 = np.arange(5,25)
print(arr1)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


1.2 Create a 2D array with 3 rows and 4 columns filled with random integers between 10 and 50. 

In [18]:
arr2 = np.random.randint(10, 50, size=(3, 4))
print(arr2)

[[44 17 11 20]
 [33 14 20 19]
 [48 41 17 25]]


Ques on 2: Array Atributes  
2.1 For the 1D array created in Question 1.1, find, and print its: 
 Shape 
 Size 
 Data type
2.2 For the 2D array created in Question 1.2, find, and print its: 
 Shape 
 Size 
 Data type

In [12]:
# array 1
print("shape:",arr1.shape)
print("size:",arr1.size)
print("dtype:",arr1.dtype)

shape: (20,)
size: 20
dtype: float64


In [13]:
# array 2
print("shape:",arr2.shape)
print("size:",arr2.size)
print("dtype:",arr2.dtype)

shape: (3, 4)
size: 12
dtype: float64


Ques on 3: Array Operations  
3.1 Create two 1D arrays:<br>
Array1: [2, 4, 6, 8, 10]<br>
Array2: [1, 3, 5, 7, 9] <br>
3.2 Perform the following operations and print the results: <br>
 Addition<br>
 Subtraction <br>
 Element-wise multiplication <br>
 Element-wise division<br>

In [14]:
my_arr1 = np.array([2,4,6,8,10])
my_arr2 = np.array([1,3,5,7,9])

print("Addition:",my_arr1 + my_arr2)
print("Subtraction:",my_arr1 - my_arr2)
print("Multiplication:",my_arr1 * my_arr2)
print("Division:",my_arr1 / my_arr2)

Addition: [ 3  7 11 15 19]
Subtraction: [1 1 1 1 1]
Multiplication: [ 2 12 30 56 90]
Division: [2.         1.33333333 1.2        1.14285714 1.11111111]


Question 4: Broadcasting <br>
4.1 Create a 2D array of shape (3, 3) with values starting from 1 to 9. <br>
4.2 Using broadcasting, multiply this 2D array by a scalar value of 5. Print the result.

In [21]:
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)
scalar = 5
print("Multiplication by scalar:\n",arr2d * scalar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Multiplication by scalar:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


Question 5: Slicing and Indexing  <br>
5.1 Create a 2D array of shape (4, 4) with values ranging from 10 to 25. <br>
5.2 Extract the second row and the last column of the array. <br>
5.3 Replace the elements of the first row with zeros.

In [28]:
arr5_1 = np.arange(10,26).reshape(4,4)
print(arr5_1)
col2 = arr5_1[:,1]
print("Column 2:",col2)
col_last = arr5_1[:,-1]
print("Last Column:",col_last)
arr5_1[0,:] = 0
print("new array:\n",arr5_1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
Column 2: [11 15 19 23]
Last Column: [13 17 21 25]
new array:
 [[ 0  0  0  0]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


Question 6: Boolean Indexing  <br>
6.1 Create a 1D array with random integers between 20 and 40 (10 elements). <br>
6.2 Use Boolean indexing to find all elements greater than 30.

In [34]:
rand_Arr = np.random.randint(20,40, size=10)
rand_Arr.sort()
print("Boolean Array:",rand_Arr)
bool_arr = rand_Arr[rand_Arr>30]
print("Boolean Array > 30:\n",bool_arr)

Boolean Array: [20 22 23 26 26 31 32 37 38 38]
Boolean Array > 30:
 [31 32 37 38 38]


Question 7: Reshaping  <br>
7.1 Create a 1D array with 12 elements starting from 11. <br>
7.2 Reshape it into a 2D array of shape (3, 4). Print the reshaped array.

In [35]:
arr7_1 = np.arange(11, 11+12)
arr7_2 = arr7_1.reshape(3,4)
print(arr7_2)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


Question 8: Matrix Operations  <br>
8.1 Create two 2x2 matrices: <br>
 Matrix A: [[1, 2], [3, 4]] <br>
 Matrix B: [[5, 6], [7, 8]] <br>
8.2 Perform and print the results of the following operations: <br>
 Matrix multiplication <br>
 Transpose of Matrix A 

In [37]:
mat_a = np.matrix([[1,2], [3,4]])
mat_b = np.matrix([[5,6], [7,8]])
print("Matrix A:\n",mat_a)
print("Matrix B:\n",mat_b)
print("Matrix Multiplication:\n",mat_a * mat_b)
print("Transpose of Matrix A:\n",mat_a.T)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of Matrix A:
 [[1 3]
 [2 4]]


9.1 Create a 1D array with random integers between 10 and 60 (15 elements). 
9.2 Compute and print the following statistics: 
 Mean 
 Median 
 Standard deviation

In [39]:
arr9_1 = np.random.randint(10, 60, size=15)
mean = np.mean(arr9_1)
median = np.median(arr9_1)
std_dev = np.std(arr9_1)
print("Array:\n", arr9_1)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)   

Array:
 [38 17 41 34 31 49 21 10 52 29 28 43 32 32 22]
Mean: 31.933333333333334
Median: 32.0
Standard Deviation: 11.215861783900316


Ques on 10: Linear Algebra  
10.1 Create a 3x3 matrix: 
A = 
[[2 1 3]
[0 5 6]
[7 8 9]]
 
10.2 Perform the following opera ons: 
 Find the determinant of matrix A. 
 Compute the inverse of matrix A. 
 Find the eigenvalues and eigenvectors of matrix A.

In [40]:
mat10_1 = np.matrix([[2,1,3], [0, 5, 6], [7, 8, 9]])

det = np.linalg.det(mat10_1)
inv = np.linalg.inv(mat10_1)
val, vec = np.linalg.eig(mat10_1)
print("Matrix:\n", mat10_1)
print("Determinant:", det)
print("Inverse:\n", inv)
print("Eigen Values:", val)
print("Eigen Vectors:\n", vec)

Matrix:
 [[2 1 3]
 [0 5 6]
 [7 8 9]]
Determinant: -68.99999999999996
Inverse:
 [[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]
Eigen Values: [15.45215427  2.40475147 -1.85690573]
Eigen Vectors:
 [[-0.22453607 -0.55941438 -0.38300969]
 [-0.48513596  0.7607706  -0.60830181]
 [-0.84511931 -0.3290648   0.69517803]]
